import { Job, Application, Notification, UserProfile } from '../types';

export const MOCK_USER: UserProfile = {
  name: "Rahul Sharma",
  role: "Senior Waiter",
  avatar: "https://picsum.photos/200/200",
  completionPercentage: 75,
  email: "rahul.sharma@example.com",
  phone: "+91 98765 43210",
  location: "Mumbai, MH",
  skills: ["Wine Service", "POS Systems", "Team Leadership"],
  experience: "5 years in fine dining",
  availability: "Weekends and Evenings",
};

export const MOCK_JOBS: Job[] = [
  {
    id: "1",
    title: "Fine Dining Waiter",
    company: "The Taj Mahal Palace",
    location: "South Mumbai, MH",
    salary: "₹500/hr + Tips",
    jobType: "Full-time",
    type: "Full-time",
    description: "Looking for an experienced server for our evening shifts. Must have wine knowledge.",
    postedAt: "2 days ago",
    matchScore: 95,
  },
  {
    id: "2",
    title: "Breakfast Server",
    company: "Irani Cafe",
    location: "Bandra, MH",
    salary: "₹300/hr + Tips",
    jobType: "Part-time",
    type: "Part-time",
    description: "Fast-paced breakfast spot needs energetic servers for weekend shifts.",
    postedAt: "1 day ago",
    matchScore: 88,
  },
  {
    id: "3",
    title: "Event Staff / Banquet Server",
    company: "Oberoi Events",
    location: "Andheri, MH",
    salary: "₹800/hr",
    jobType: "Casual",
    type: "Casual",
    description: "Join our on-call roster for weddings and corporate events.",
    postedAt: "4 hours ago",
    matchScore: 70,
  },
  {
    id: "4",
    title: "Bartender / Server",
    company: "The Bombay Canteen",
    location: "Navi Mumbai, MH",
    salary: "₹400/hr + Tips",
    jobType: "Full-time",
    type: "Full-time",
    description: "Experience with cocktail mixing is a plus. Fun environment.",
    postedAt: "1 week ago",
    matchScore: 82,
  },
];

export const MOCK_APPLICATIONS: Application[] = [
  {
    id: "a1",
    jobId: "2",
    jobTitle: "Breakfast Server",
    company: "Irani Cafe",
    applicantId: "user1",
    status: "Shortlisted",
    date: "2023-10-25",
  },
  {
    id: "a2",
    jobId: "5",
    jobTitle: "Dinner Host",
    company: "Barbeque Nation",
    applicantId: "user1",
    status: "Rejected",
    date: "2023-10-20",
  },
  {
    id: "a3",
    jobId: "6",
    jobTitle: "Head Waiter",
    company: "Trattoria Mumbai",
    applicantId: "user1",
    status: "Interview",
    date: "2023-10-28",
  },
  {
    id: "a4",
    jobId: "1",
    jobTitle: "Fine Dining Waiter",
    company: "The Taj Mahal Palace",
    applicantId: "user1",
    status: "Applied",
    date: "2023-10-29",
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: "n1",
    title: "Interview Scheduled",
    message: "Your interview with Trattoria Mumbai is set for tomorrow at 2 PM.",
    date: "1 hour ago",
    read: false,
    type: "success",
  },
  {
    id: "n2",
    title: "Profile Viewed",
    message: "The Taj Mahal Palace viewed your profile.",
    date: "5 hours ago",
    read: true,
    type: "info",
  },
  {
    id: "n3",
    title: "Application Update",
    message: "Irani Cafe has shortlisted your application.",
    date: "1 day ago",
    read: true,
    type: "success",
  },
];
